# Generated by Django 2.1.8 on 2019-04-22 12:15

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='GPU',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.TextField()),
                ('imgsrc', models.TextField()),
                ('price', models.CharField(max_length=20)),
                ('commentNum', models.CharField(max_length=20)),
            ],
            options={
                'db_table': 'GPU',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='MovieList',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mname', models.TextField()),
                ('content', models.TextField()),
                ('data', models.DateField()),
                ('actor', models.CharField(max_length=20)),
                ('imgsrc', models.TextField()),
            ],
            options={
                'db_table': 'movieList',
                'managed': True,
            },
        ),
    ]
